### ISSUE TITLE
How i can intergate with Prism Unity?

### ISSUE THREAD

**Issue by ghost** [anakic/Jot#20]
i found Jot.Unity but how use it?

**Comment by lorinkundert** [comment]
I use ReactiveUI so it is more complicated but the concepts are the same, in your Program.cs or a BootStrapper class, I use 

Locator.CurrentMutable.RegisterConstant(PersistanceService.Tracker, typeof(Tracker)); 

PersistanceService is the class you can find in the samples and documentation, it may have a different name, the next step is to use the service like so, 
 
"Locator.Current.GetService<Tracker>().Track(this);"

**Comment by anakic** [comment]
So this is an old issue that I never got around to answering. It's a few years too late now, especially since it seems Unity is no longer maintained, but I'm closing old issues so here's the answer...

I use the following extension to apply tracking to all resolved objects:

```csharp
public class TrackingExtension : UnityContainerExtension
{
    class TrackingStrategy : BuilderStrategy
    {
        readonly Tracker tracker;
        public TrackingStrategy(IUnityContainer container)
        {
            tracker = container.Resolve<Tracker>();
        }

        public override void PostBuildUp(ref BuilderContext context)
        {
            base.PostBuildUp(ref context);
            if (RemotingServices.IsTransparentProxy(context.Existing) == false)
            {
                Type targetType = context.Existing.GetType();
                tracker.Track(context.Existing);
            }
        }
    }

    protected override void Initialize()
    {
        Context.Strategies.Add(new TrackingStrategy(Container), UnityBuildStage.Creation);
    }
}
```
I register it with the container like so: `container.AddExtension(new TrackingExtension());`.

Sorry about the extremely late reply.
