### ISSUE TITLE
Maximize window on correct monitor

### ISSUE THREAD

**Issue by Marv51** [anakic/Jot#3]
If a window is maximized it appears to not get restored on the correct monitor. In my testing the window always gets restored on the primary screen.

According to http://mostlytech.blogspot.de/2008/01/maximizing-wpf-window-to-second-monitor.html and https://social.msdn.microsoft.com/Forums/vstudio/en-US/2ca2fab6-b349-4c08-915f-373c71bd636a/show-and-maximize-wpf-window-on-a-specific-screen?forum=wpf
The WindowState Property should be applied after the window loaded event was fired.

Moving the call to .Apply() to the LoadedEvent handler on the window fixes this problem.

But maybe there could be a more elegant solution?

It is getting quite complicated, my "minimal" window setup:

```
public partial class ProjectView : Window
    {
        private TrackingConfiguration JotTracker;

        public ProjectView()
        {
            InitializeComponent();

            JotTracker = StateTrackerService.Tracker.Configure(this);
            JotTracker.ApplyingProperty += StateTrackerService.StateConfig_ApplyingProperty;
            JotTracker.IdentifyAs("ProjectView")
               .AddProperties<ProjectView>(w => w.Height, w => w.Width, w => w.Left, w => w.Top, w => w.WindowState)
               .RegisterPersistTrigger(nameof(Closed));

                Loaded += ProjectView_Loaded;
        }

        private void ProjectView_Loaded(object sender, RoutedEventArgs e)
        {
            JotTracker.Apply();
        }
}
```

**Comment by anakic** [comment]
Hi Marv. I've just tested with the demo WPF applications and it works fine even with the code in the constructor. Can you give the "TestWpf" demo project a try and see if it works on your machine?

**Comment by anakic** [comment]
Oh, and pull the latest version, I had to update the demo projects to .NET 4.5.2. they were outdated.

**Comment by SCKelemen** [comment]
Does this work with multiple windows?

**Comment by anakic** [comment]
Yep, you just need to make sure you identify each window with its name using the IdentifyAs() method like Marv did above.

**Comment by anakic** [comment]
@Marv51 I just noticed the "if a window is maximized" part. Yeah, just checked and you're right, it will always get restored to the main screen. Been working with WPF for years and never noticed that issue...

Someone in the comments of the link you sent suggested using the `windows.SourceInitialized` event, as this removes the flicker (I checked, it does). 

One thing you can do is move all the Jot code from the constructor to the SourceInitialized eventhandler. That way it's not scattered about. It's only executed once per window (I'm guessing) anyway.

Another solution might be to make a static helper method like SetupWindowTracking(Window window, StateTracker tracker). You could call this method from the constructor of any window. The method would subscribe to the windows's `SourceInitialized` event and set up tracking for it. You could pass `window.Name` to `IdentifyAs()` to identify the window.

If you're using an IOC container, you could make this a post build step, so that all windows (that are created via IOC) get this behavior out of the box.

Any of this make sense?

**Comment by Marv51** [comment]
Thanks for this great response.

The SourceInitialized thing is a good idea. And I will move all my code there. 
Passing window.name to Jot is a good idea too. 
Currently I don't use any IOC thing, so I will probably build a window subclass.

Maybe you could copy some of this advice to the documentation?

**Comment by anakic** [comment]
@Marv51 Just wanted to let you know that I've made some improvements in the library, some of them based on this conversation and the previous one. 

Now you can tell the StateTracker how to configure tracking for all objects of a certain type (e.g. for all Window objects). The feature is based on the new `IConfigurationInitializer`interface. Out of the box, the StateTracker includes a configuration initializer for `Window` objects, so to track a WPF Window, all you need to do is this:

`this.SourceInitialized += (s, e) => tracker.Configure(window).Apply();`

The `WindowConfigurationInitializer` (that's installed by default) will adjust the configuration for the window and will handle all the edge cases related to multiple displays.
