### ISSUE TITLE
Strange json file name

### ISSUE THREAD

**Issue by anders-eriksson** [anakic/Jot#32]
Instead of getting a filename like this _MainWindow_MainWindow.json_
I get this **{Width=1920, Height=1200}..json**

What have I done wrong?

Using VS2019, WPF, .NET Framework 4.7.2, Jot 2.0.1

// Anders

**Comment by anakic** [comment]
Hi Anders. 

The only thing that's missing is that you did not give a name to your window. You should set the window's Name property before tracking it so Jot can disambiguate between it and other tracked window instances.

The resolution is part of the file name intentionally (you specify it in the Id(...) method), and the reason for this is to use different data for different screen resolutions so that you don't have forms displaying off-screen (e.g. you unplug a display between two work sessions).

**Comment by anders-eriksson** [comment]
OK! 
Thanks for Jot and for the answer!
