### ISSUE TITLE
can not restore setting of textbox and checkedlistbox

### ISSUE THREAD

**Issue by greenoaktree** [anakic/Jot#4]
Services.Tracker.Configure(textBox1).AddProperties<TextBox>(tb => tb.Text).Apply();
Services.Tracker.Configure(checkedListBox1).AddProperties<CheckedListBox>(clb => clb.CheckedIndices).Apply();

**Comment by anakic** [comment]
Hey, thanks for reporting. 

**Quick answer:**
tracker.Configure(textBox1).RegisterPersistTrigger("TextChanged").SetAutoPersistEnabled(false).AddProperties<TextBox>(c => c.Text).Apply();

**Long answer:**
The issue is due to the fact that some controls get disposed and lose data before the `Application.ApplicationExit` event. Textbox, for instance, will have its `Text` property set to "" when it gets disposed.

The properties need to get persisted earlier. You can do one of two things:
1. if possible, don't track the controls themselves, but track the underlying data object that the control is bound to. E.g. a texbox is most probably a gui for a string property on some object (e.g. a FirstName property of a Person object). Track that property instead.
2. Set the persist trigger, and disable automatic persist, like so:
   `tracker.Configure(textBox1).RegisterPersistTrigger("TextChanged").SetAutoPersistEnabled(false).AddProperties<TextBox>(c => c.Text).Apply();`

Although I'd suggest option 1, tracking GUI objects isn't necessarily bad and this could be a common issue so the following modifications to the library could fix the issue for the future:
1. Find an event that gets fired just before the application closes, but before controls get disposed. If such an event exists, use that in the DesktopPersistTrigger class.
2. Add configuration initializers for all common controls so that people don't even have to mess with the configurations for a control, they would just do `tracker.Configure(someControl)..Apply();`

**Comment by greenoaktree** [comment]
Thanks,textbox work fine now!
But CheckedListBox 's CheckedIndices Property is readonly ,how to persist CheckedListBox status?

**Comment by anakic** [comment]
Currently, it won't work on properties that don't have setters. I might add an event for handling setting for such properties in the future, but I would suggest a different approach.

To handle this scenario, I'd suggest tracking the underlying object that the UI is representing, instead of the UI controls themselves. That, I think, is the healthier option in all situations, except for data that is explicitly UI-related.

For example, tracking the size and location of a Form is ok because this data is explicitly UI related. Tracking the text in a TexBox, or a Checked property of a CheckBox is probably not the right approach since they probably represent properties of some other object (which you should be tracking instead).

Alternatively, if you really want to track the UI objects themselves, you can do something like this for a CheckedListBox (which is way more manual work, similar to using a settings file, but will do the trick):

``` C#
 //maually create a store for our object
var clbStore = tracker.StoreFactory.CreateStoreForObject(checkedListBox1.Name);
clbStore.Initialize();
string propertyName = nameof(CheckedListBox.CheckedIndices);
if (clbStore.ContainsKey(propertyName))
{
    var selectedIndices = (int[])clbStore.Get(propertyName);
    foreach (int i in selectedIndices)
        checkedListBox1.SetItemChecked(i, true);
}
//json.net won't know how to deserialize CheckedIndexCollection so we're converting it to array.
this.FormClosed += (s, e) => { clbStore.Set(checkedListBox1.CheckedIndices.OfType<int>().ToArray(), propertyName); clbStore.CommitChanges(); };
```
