### ISSUE TITLE
Support for System.Text.Json

### ISSUE THREAD

**Issue by daniel-rck** [anakic/Jot#50]
Are you considering/planning to support System.Text.Json insteaf of Newtonsoft.Json?

**Comment by anakic** [comment]
It would be fairly easy to do, but I'm not sure if there's a benefit to it. Any pros/cons you can think of @daniel-rck?

**Comment by daniel-rck** [comment]
Maybe this can give you feedback: https://devblogs.microsoft.com/dotnet/whats-next-for-system-text-json/#choosing-between-system-text-json-and-newtonsoft-json

Personally I guess System.Text.Json will evolve more and will be faster than Newtonsoft's.

**Comment by anakic** [comment]
I was put off by the number of dll dependencies that are download with it. The total size is roughly the same, though, so it's not much of a factor. For now I don't see a good reason to switch, but if one pops up, I won't mind.

**Comment by geferon** [comment]
I know this is closed but now that System.Text.Json is more mainstream and relevant, do you think there would be a chance you could implement it? Could be as simple as having a core Jot package and then two separate ones, one for Newtonsoft Json and one for System.Text.Json, since it's just as simple as implementing IStore
