### ISSUE TITLE
Persist and load Net 6 TimeOnly type

### ISSUE THREAD

**Issue by maeyanes** [anakic/Jot#62]
Hi...

I'm using Jot in a project with Net 6 and WPF.

When I try to store and load properties of type TimeOnly, the first time, the properties are persisted fine, but in next application run, the values are not loaded and my properties are all with values of 0:0 (0 hours, 0 minutes).

**Comment by anakic** [comment]
@maeyanes excuse the late reply. 

That issue happens because the current version of Newtonsoft.Json (13.0.1.) [doesn't yet support](https://github.com/JamesNK/Newtonsoft.Json/issues/2521) DateOnly and TimeOnly types. It looks like this will be fixed in the next version of Newtonsoft.Json, though when that might come out I don't know. 

I plan to make serialization a bit more configurable in the future but it's likely that the next version of Newtonsoft.Json will come out before I make that change.

**Comment by maeyanes** [comment]
Thanks!

Meanwhile I'm using full DateTime.
